# Generated by Django 2.0.2 on 2018-05-13 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180511_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flagged_reason',
            field=models.CharField(blank=True, choices=[('offensive', 'Offensive'), ('abusive', 'Abusive'), ('lacks-credibility', 'Lacks Credibility')], max_length=18),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
