# Generated by Django 2.0.2 on 2018-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180513_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='app.Answer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='app.Comment'),
        ),
    ]
