# Generated by Django 2.0.2 on 2018-05-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180513_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
