# Generated by Django 2.0.2 on 2018-05-13 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180513_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='region',
        ),
    ]
