# Generated by Django 2.0.2 on 2018-05-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_post_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
