# Generated by Django 2.0.2 on 2018-05-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_post_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='region',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
    ]
