# Generated by Django 2.0.2 on 2018-05-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180514_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='country',
            new_name='country_name',
        ),
    ]
